name: video_player_harmonyos
description: "HarmonyOS implementation of the video_player plugin."
version: 0.0.1
repository: https://github.com/Wayaer/harmony_flutter_packages/tree/main/video_player_harmonyos

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^6.4.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: video_player
    platforms:
      ohos:
        pluginClass: VideoPlayerPlugin
        dartPluginClass: VideoPlayerHarmonyOS
