name: package_info_plus_harmonyos_example
description: "Demonstrates how to use the package_info_plus_harmonyos plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.1
  package_info_plus_harmonyos:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
