name: path_provider_harmonyos
description: "HarmonyOS implementation of the path_provider plugin."
version: 0.0.1
repository: https://github.com/Wayaer/harmony_flutter_packages/tree/main/path_provider_harmonyos

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider_platform_interface: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: path_provider
    platforms:
      ohos:
        pluginClass: PathProviderPlugin
        dartPluginClass: PathProviderHarmonyOS
