name: in_app_purchase_ohos
description: An implementation for the Ohos platform of the Flutter `in_app_purchase` plugin. This uses the ohoa IAPKit APIs.
repository: https://gitee.com/openharmony-sig/flutter_packages/tree/master/packages/in_app_purchase/in_app_purchase_ohos
issue_tracker: https://gitee.com/openharmony-sig/flutter_packages/issues
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  in_app_purchase_platform_interface: ^1.3.0
  json_annotation: ^4.8.0

flutter:
  plugin:
    implements: in_app_purchase
    platforms:
      ohos:
        pluginClass: InAppPurchasePlugin

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  flutter_lints: ^5.0.0