name: permission_handler_harmonyos
description: "HarmonyOS implementation of the permission_handler plugin."
version: 0.0.1
repository: https://github.com/Wayaer/harmony_flutter_packages/tree/main/permission_handler_harmonyos

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface: ^4.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: permission_handler
    platforms:
      ohos:
        pluginClass: PermissionHandlerPlugin
