name: image_picker_harmonyos_example
description: "Demonstrates how to use the image_picker_harmonyos plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mime: ^2.0.0
  image_picker: ^1.2.0
  image_picker_harmonyos:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
