name: path_provider_harmonyos_example
description: "Demonstrates how to use the path_provider_harmonyos plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  path_provider_harmonyos:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
