name: wakelock_plus_harmonyos
description: "HarmonyOS implementation of the wakelock_plus plugin."
version: 0.0.1
repository: https://github.com/Wayaer/harmony_flutter_packages/tree/main/file_selector_harmonyos

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus_platform_interface: ^1.2.3

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: wakelock_plus
    platforms:
      ohos:
        pluginClass: WakelockPlusPlugin
