name: image_picker_harmonyos
description: "HarmonyOS implementation of the image_picker plugin."
version: 0.0.1
repository: https://github.com/Wayaer/harmony_flutter_packages/tree/main/image_picker_harmonyos

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface: ^2.8.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: image_picker
    platforms:
      ohos:
        pluginClass: ImagePickerPlugin
        dartPluginClass: ImagePickerHarmonyOS
