name: file_selector_harmonyos
description: "HarmonyOS implementation of the file_selector plugin."
version: 0.0.1
repository: https://github.com/Wayaer/harmony_flutter_packages/tree/main/file_selector_harmonyos

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  file_selector_platform_interface: ^2.6.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: file_selector
    platforms:
      ohos:
        pluginClass: FileSelectorPlugin
        dartPluginClass: FileSelectorHarmonyOS
